### ISSUE TITLE
Packaging Conda Forge

### ISSUE THREAD

**Issue by alevieux** [umr-lops/xsar#10]
Adding a package in conda-forge for simplify the xsar installation

Expected result : `conda install -c conda-forge xsar`

We have a stable realease xsar-v0.5 in develop branch 

Step by step: 

1. Create a master branche in git with specific tag for release to isolate  develop and distributed version
2. Follow the conda-forge [tutorial](https://conda-forge.org/docs/maintainer/adding_pkgs.html)

**Comment by alevieux** [comment]
# Progress update of subject

Actually I generate a build xsar with [conda-build ](https://docs.conda.io/projects/conda-build/en/latest/index.html).

I apply to conda-build the specific file meta.yaml ( it's the file to send in a recipe for conda-forge):
```
{% set name = "xsar" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/umr-lops/{{ name|lower }}/archive/refs/tags/v{{ version }}.tar.gz

build:
  number: 0
  script: "pip install --no-deps ."

requirements:
  host:
    - python
    - pip
    - gdal
    - rasterio
    - cartopy
    - dask
  run:
    - gdal >=3.2.1
    - rasterio >=1.2.6
    - cartopy >=0.19.0
    - dask >=2021.6.2

test:
  imports:
    - xsar

about:
  home: https://github.com/umr-lops/xsar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'xsar is a distributed level 1 SAR file reader'
  description: "xsar is a distributed level 1 SAR file reader designed to write efficient distributed processing algorhitm with xarray and dask."
  doc_url: https://cyclobs.ifremer.fr/static/sarwing_datarmor/xsar/index.html
  dev_url: https://github.com/umr-lops/xsar

extra:
  recipe-maintainers:
    - ArcherOlivier
    - LevieuxAlexandre
```

- dependancies installation with good version -> OK
- install xsar no work but I think it's just a modification in setup.py or pip install command option


For information : [Grayskull](https://github.com/conda-incubator/grayskull) is the future of packaging but now it's just for pypi project, not for us now
